[profile.default]
src = "src"
out = "out"
auto_detect_solc = false
solc = "0.8.30"
ffi = true
ast = true
viaIR = true
build_info = true
extra_output = ["storageLayout"]
verbosity = 3
optimizer = true
optimizer_runs = 20_000
libs = ["lib"]

remappings = [
    '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/',
    'solidity-bytes-utils/contracts/=lib/solidity-bytes-utils/contracts/',
    '@layerzerolabs/oft-evm/=lib/devtools/packages/oft-evm/',
    '@layerzerolabs/oapp-evm/=lib/devtools/packages/oapp-evm/',
    '@layerzerolabs/lz-evm-protocol-v2/=lib/layerzero-v2/packages/layerzero-v2/evm/protocol',
    '@layerzerolabs/lz-evm-messagelib-v2/=lib/layerzero-v2/packages/layerzero-v2/evm/messagelib',
    '@layerzerolabs/test-devtools-evm-foundry/=lib/devtools/packages/test-devtools-evm-foundry/',
    '@layerzerolabs/lz-evm-v1-0.7/contracts/=lib/layerzero-v1/contracts/',    
]

[rpc_endpoints]
mainnet = "https://mainnet.infura.io/v3/3a0fa033ac184bd6bdea8aa7d910614f"
sepolia = "https://sepolia.infura.io/v3/3a0fa033ac184bd6bdea8aa7d910614f"
base = "https://mainnet.base.org"
base-sepolia = "https://sepolia.base.org"
arbitrum = "https://arb1.arbitrum.io/rpc"
arbitrum-sepolia = "https://arbitrum-sepolia.gateway.tenderly.co"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}", url = "https://api.etherscan.io/v2/api?chainid=1" }
sepolia = { key = "${ETHERSCAN_API_KEY}", url = "https://api.etherscan.io/v2/api?chainid=11155111"  }
base = { key = "${ETHERSCAN_API_KEY}", url = "https://api.etherscan.io/v2/api?chainid=8453" }
base-sepolia = { key = "${ETHERSCAN_API_KEY}", url = "https://api.etherscan.io/v2/api?chainid=84532" }
arbitrum = { key = "${ETHERSCAN_API_KEY}", url = "https://api.etherscan.io/v2/api?chainid=42161" }
arbitrum-sepolia = { key = "${ETHERSCAN_API_KEY}", url = "https://api.etherscan.io/v2/api?chainid=421614" }
